version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  style_guide = "google"
  plugins = ["react"]
  environment = ["nodejs"]

[[transformers]]
name = "prettier"
enabled = true